name: Run scraper

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
  
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: requirements.txt

      - name: Run final-scraper.py
        run: python final-scraper.py

      - name: Compare scraped data
        run: |
          diff=$(diff scraped_data.json scraped_data_new.json)
          if [ -n "$diff" ]; then
            echo "Changes detected in scraped data"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add scraped_data.json
            git commit -m "Update scraped data"
            git push
          else
            echo "No changes detected in scraped data"
          fi